version: '2'
services:
        api:
                build:
                        context: ./api
                ports:
                        - "3001:3001"
                depends_on:
                        - redis
                environment:
                        - REDIS=redis://redis:6379/
        web:
                build:
                        context: ./web
                ports:
                        - "80:3000"
        redis:
                image: "redis:alpine"
                ports:
                        -  "6379:6379"

