version: '2'
services:
        api:
                build:
                        context: ./api
                ports:
                        - "8000:8000"
        web:
                build:
                        context: ./web
                ports:
                        - "8080:80"
